### ISSUE TITLE
Plain Text Rendering Remove Duplicate Characters

### ISSUE THREAD

**Issue by rcmoret** [beaucouplus/ruby_portable_text#5]
There's an issue when using the plain serializer. The `squeeze` method will remove any duplicate characters. 

```
"comme pomme de terre".squeeze
# =>"come pome de tere"
```
I submitted a [pull request](https://github.com/beaucouplus/ruby_portable_text/pull/4) to address the issue.

**Comment by beaucouplus** [comment]
Hello Ryan,

Thanks a lot, I'll get some time in the upcoming days to review and merge your PR and hopefully release a new gem version with the fix! I feel dumb for confusing both methods 🫠

**Comment by beaucouplus** [comment]
Thanks again, I updated the gem with your PR 🙏🏼
